"""F-Stack: f-stack.conf generation, VXLAN setup through the F-Stack tools
(ff_ifconfig / ff_route / ff_arp) and CPU accounting through ff_top."""

import os
import re
import threading
import time

from .util import Proc, cpu_mask_hex, debug, die, run, warn


def gen_conf(cores, pcis, topology, plan, s2, bond_mode, bond_policy, vip_count):
    """cores: lcores used by F-Stack (one nginx worker each)."""
    allow = ",".join(pcis)
    L = []
    L.append("# generated by fbench (scenario 2, F-Stack nginx)")
    L.append("[dpdk]")
    L.append("lcore_mask=%s" % cpu_mask_hex(cores))
    L.append("channel=4")
    L.append("promiscuous=1")
    L.append("numa_on=1")
    L.append("tx_csum_offoad_skip=0")
    L.append("tso=%d" % s2["fstack_tso"])
    L.append("vlan_strip=1")
    L.append("idle_sleep=0")
    L.append("pkt_tx_delay=%d" % s2["fstack_pkt_tx_delay"])
    L.append("symmetric_rss=0")
    if allow:
        L.append("allow=%s" % allow)
    if topology == "bond":
        L.append("port_list=2")
        L.append("nb_bond=1")
    elif topology == "dual":
        L.append("port_list=0,1")
        L.append("nb_bond=0")
    else:
        L.append("port_list=0")
        L.append("nb_bond=0")
    L.append("nb_vdev=0")
    L.append("")
    L.append("[pcap]")
    L.append("enable=0")
    L.append("")

    def port_section(sec_id, idx, extra=()):
        L.append("[port%d]" % sec_id)
        L.append("addr=%s" % plan.server_ip[idx])
        L.append("netmask=%s" % plan.netmask())
        L.append("broadcast=%s" % plan.broadcast(idx))
        # default route towards the dperf client: its source ranges are behind it
        L.append("gateway=%s" % plan.client_ip[idx])
        if vip_count:
            vips = [plan.add(plan.server_range[idx], k) for k in range(vip_count)]
            L.append("vip_addr=%s" % ";".join(vips))
        for e in extra:
            L.append(e)
        L.append("")

    if topology == "bond":
        port_section(2, 0, ["slave_port_list=0,1"])
        L.append("[bond0]")
        L.append("mode=%d" % bond_mode)
        L.append("slave=%s" % ",slave=".join(pcis[:2]))
        L.append("xmit_policy=%s" % bond_policy)
        # lsc_poll_period_ms/up_delay/down_delay are rejected by the bonding
        # PMD at probe ("Invalid args"), so they are not set
        L.append("")
    elif topology == "dual":
        port_section(0, 0)
        port_section(1, 1)
    else:
        port_section(0, 0)

    L.append("[freebsd.boot]")
    L.append("hz=100")
    L.append("fd_reserve=1024")
    L.append("kern.ipc.maxsockets=262144")
    L.append("net.inet.tcp.syncache.hashsize=4096")
    L.append("net.inet.tcp.syncache.bucketlimit=100")
    L.append("net.inet.tcp.tcbhashsize=65536")
    L.append("kern.ncallout=262144")
    L.append("kern.features.inet6=1")
    L.append("")
    L.append("[freebsd.sysctl]")
    L.append("kern.ipc.somaxconn=32768")
    L.append("kern.ipc.maxsockbuf=16777216")
    L.append("net.add_addr_allfibs=1")
    L.append("net.link.ether.inet.maxhold=5")
    L.append("net.inet.tcp.fast_finwait2_recycle=1")
    L.append("net.inet.tcp.finwait2_timeout=5000")
    L.append("net.inet.tcp.maxtcptw=128")
    L.append("net.inet.tcp.sendspace=%d" % s2["fstack_sendspace"])
    L.append("net.inet.tcp.recvspace=%d" % s2["fstack_recvspace"])
    L.append("net.inet.tcp.cc.algorithm=cubic")
    L.append("net.inet.tcp.sendbuf_max=16777216")
    L.append("net.inet.tcp.recvbuf_max=16777216")
    L.append("net.inet.tcp.sendbuf_auto=1")
    L.append("net.inet.tcp.recvbuf_auto=1")
    L.append("net.inet.tcp.sendbuf_inc=16384")
    L.append("net.inet.tcp.sack.enable=1")
    L.append("net.inet.tcp.blackhole=1")
    L.append("net.inet.tcp.msl=2000")
    L.append("net.inet.tcp.delayed_ack=1")
    L.append("net.inet.tcp.rfc1323=1")
    L.append("net.inet.udp.blackhole=1")
    L.append("net.inet.ip.redirect=0")
    L.append("net.inet.ip.forwarding=0")
    L.append("net.inet.ip.portrange.randomized=1")
    L.append("net.inet.ip.portrange.randomtime=0")
    L.append("net.inet.tcp.functions_default=freebsd")
    return "\n".join(L) + "\n"


def fstack_ifname(topology, idx):
    if topology == "bond":
        return "f-stack-2"
    return "f-stack-%d" % idx


class Tools(object):
    def __init__(self, tools_dir):
        self.dir = tools_dir

    def path(self, name):
        p = os.path.join(self.dir, name)
        if not os.path.isfile(p):
            alt = "/usr/local/bin/ff_%s" % name
            if os.path.isfile(alt):
                return alt
            die("F-Stack tool %s not found (run ./build.sh on the server, or set fstack_tools)" % p)
        return p

    def call(self, name, proc_id, args, check=True, timeout=60):
        cmd = [self.path(name), "-p", str(proc_id)] + list(args)
        rc, out = run(cmd, check=False, timeout=timeout)
        if rc != 0 and check:
            die("%s failed (rc=%d): %s" % (" ".join(cmd), rc, out.strip()[-800:]))
        return rc, out

    def alive(self, proc_id):
        rc, out = self.call("ifconfig", proc_id, ["-a"], check=False, timeout=30)
        return rc == 0 and "f-stack" in out


MAC_RE = re.compile(r"^\s*ether\s+([0-9a-fA-F:]{17})", re.M)


def setup_vxlan(tools, nprocs, topology, plan, ports, client_vteps):
    """Create vxlanN on every F-Stack process (each one is an independent
    FreeBSD stack instance). Returns the MAC of vxlanN per port: F-Stack's
    ifconfig cannot change it, FreeBSD derives it from hostuuid + ifname, so it
    is the same in every process and the dperf client uses it as inner dmac."""
    macs = [None] * ports
    for proc_id in range(nprocs):
        for idx in range(ports):
            vx = "vxlan%d" % idx
            tools.call("ifconfig", proc_id, [vx, "create", "vxlanid", str(plan.vni[idx]),
                                             "vxlanlocal", plan.server_ip[idx],
                                             "vxlanremote", client_vteps[idx]])
            tools.call("ifconfig", proc_id, [vx, "inet", "%s/24" % plan.inner_server_ip[idx],
                                             "mtu", "1450", "up"])
            gw = plan.inner_gw(idx)
            tools.call("arp", proc_id, ["-s", gw, plan.client_inner_mac])
            tools.call("route", proc_id, ["add", "-net", plan.net16(plan.client_range[idx]), gw])
            rc, out = tools.call("ifconfig", proc_id, [vx])
            m = MAC_RE.search(out)
            if not m:
                die("cannot read the MAC of %s in F-Stack process %d:\n%s" % (vx, proc_id, out))
            mac = m.group(1).lower()
            if macs[idx] is None:
                macs[idx] = mac
            elif macs[idx] != mac:
                die("%s has different MACs in F-Stack processes (%s vs %s): one dperf inner "
                    "dmac cannot reach all of them" % (vx, macs[idx], mac))
    debug("F-Stack VXLAN configured on %d processes, MACs %s" % (nprocs, macs))
    return macs


TOTAL_RE = re.compile(r"^\|\s*total\|\s*([\d.]+)%\|\s*([\d.]+)%\|\s*([\d.]+)%\|\s*(\d+)\|")


class TopSampler(object):
    """Runs ff_top during the measurement window; effective busy cores are
    (sys+usr)/100 summed over all F-Stack processes."""

    def __init__(self, tools, nprocs, log_path):
        self.samples = []
        self.t0 = time.time()
        self.proc = None
        args = [tools.path("top"), "-p", "0", "-P", str(max(0, nprocs - 1)), "-d", "1"]
        self.proc = Proc(args, log_path, on_line=self._line)

    def _line(self, line):
        m = TOTAL_RE.match(line.strip())
        if m:
            idle, sys_, usr = float(m.group(1)), float(m.group(2)), float(m.group(3))
            self.samples.append({"t": time.time() - self.t0, "idle": idle, "sys": sys_,
                                 "usr": usr, "busy_cores": (sys_ + usr) / 100.0})

    def stop(self):
        if self.proc:
            self.proc.stop(timeout=5)
        if not self.samples:
            return {"samples": 0}
        n = float(len(self.samples))
        return {
            "samples": len(self.samples),
            "busy_cores": sum(s["busy_cores"] for s in self.samples) / n,
            "sys_pct": sum(s["sys"] for s in self.samples) / n,
            "usr_pct": sum(s["usr"] for s in self.samples) / n,
            "idle_pct": sum(s["idle"] for s in self.samples) / n,
            "series": self.samples,
        }
