"""nginx (kernel and F-Stack builds of the same source): configs and lifecycle."""

import os
import socket
import time

from .util import die, info, kill_exe, pids_of, read_file, run, size_label, wait_until, warn, \
    write_file

DOCROOT = "/dev/shm/fbench-www"
SMALL_PATH = "/s"


def bw_path(size):
    return "/bw_%s.bin" % size_label(size)


def make_docroot(bw_sizes):
    os.makedirs(DOCROOT, exist_ok=True)
    for size in bw_sizes:
        p = DOCROOT + bw_path(size)
        if not os.path.isfile(p) or os.path.getsize(p) != size:
            chunk = (b"0123456789abcdef" * 4096)
            with open(p, "wb") as f:
                left = size
                while left > 0:
                    f.write(chunk[:min(left, len(chunk))])
                    left -= len(chunk)
    return DOCROOT


def affinity_masks(cores):
    return " ".join(bin(1 << c)[2:] for c in cores)


def gen_conf(stack, run_dir, workers, cores, small_body, s2, fstack_conf=None):
    body = ("x" * (small_body - 1)) + "\n" if small_body > 0 else ""
    L = []
    L.append("# generated by fbench (scenario 2, %s stack)" % stack)
    L.append("user root;")
    L.append("worker_processes %d;" % workers)
    if stack == "kernel":
        L.append("worker_cpu_affinity %s;" % affinity_masks(cores))
    else:
        L.append("fstack_conf %s;" % fstack_conf)
    L.append("worker_rlimit_nofile 262144;")
    L.append("pid %s/nginx.pid;" % run_dir)
    L.append("error_log %s/logs/error.log warn;" % run_dir)
    L.append("")
    L.append("events {")
    if stack == "kernel":
        L.append("    worker_connections 65536;")
        L.append("    use epoll;")
    else:
        L.append("    worker_connections 102400;")
        L.append("    use kqueue;")
    L.append("    multi_accept on;")
    L.append("    accept_mutex off;")
    L.append("}")
    L.append("")
    L.append("http {")
    L.append("    access_log off;")
    L.append("    server_tokens off;")
    L.append("    default_type application/octet-stream;")
    if stack == "kernel" and s2["kernel_sendfile"]:
        L.append("    sendfile on;")
        L.append("    tcp_nopush on;")
    else:
        # F-Stack cannot sendfile() host files into its own stack
        L.append("    sendfile off;")
        L.append("    output_buffers %s;" % s2["nginx_output_buffers"])
    L.append("    tcp_nodelay on;")
    L.append("    keepalive_timeout 300s;")
    L.append("    keepalive_requests 1000000000;")
    L.append("    reset_timedout_connection on;")
    L.append("    open_file_cache max=1000 inactive=600s;")
    L.append("    open_file_cache_valid 600s;")
    L.append("    open_file_cache_errors on;")
    for t in ("client_body", "proxy", "fastcgi", "uwsgi", "scgi"):
        L.append("    %s_temp_path %s/tmp/%s;" % (t, run_dir, t))
    L.append("")
    L.append("    server {")
    if stack == "kernel":
        L.append("        listen 80 reuseport backlog=65535 default_server;")
    else:
        L.append("        listen 80 backlog=65535 default_server;")
    L.append("        server_name _;")
    L.append("        root %s;" % DOCROOT)
    L.append("        location = %s {" % SMALL_PATH)
    L.append("            default_type text/plain;")
    L.append("            return 200 \"%s\";" % body.replace("\n", "\\n"))
    L.append("        }")
    L.append("        location / {")
    L.append("        }")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


class Nginx(object):
    def __init__(self, binary, run_dir, conf_text):
        if not os.path.isfile(binary):
            die("nginx binary not found: %s (run ./build.sh or set nginx_* in [paths])" % binary)
        self.bin = binary
        self.run_dir = run_dir
        for d in ("logs", "tmp"):
            os.makedirs(os.path.join(run_dir, d), exist_ok=True)
        self.conf = os.path.join(run_dir, "nginx.conf")
        write_file(self.conf, conf_text)

    def test(self):
        rc, out = run([self.bin, "-t", "-p", self.run_dir + "/", "-c", self.conf], check=False,
                      timeout=60)
        if rc != 0:
            die("nginx -t failed:\n%s" % out.strip()[-1500:])

    def start(self):
        kill_exe(self.bin)
        run([self.bin, "-p", self.run_dir + "/", "-c", self.conf], timeout=120)

    def error_log_tail(self, n=30):
        txt = read_file(os.path.join(self.run_dir, "logs", "error.log"), "") or ""
        return "\n".join(txt.splitlines()[-n:])

    def wait_workers(self, workers, timeout):
        ok = wait_until(lambda: len(pids_of(self.bin)) >= workers + 1, timeout,
                        what="nginx workers")
        if not ok:
            die("nginx did not start %d workers (running: %d)\n%s" %
                (workers, len(pids_of(self.bin)), self.error_log_tail()))

    def check_alive(self):
        return len(pids_of(self.bin)) > 0

    def stop(self):
        if pids_of(self.bin):
            run([self.bin, "-p", self.run_dir + "/", "-c", self.conf, "-s", "stop"],
                check=False, timeout=30, quiet=True)
            wait_until(lambda: not pids_of(self.bin), 20, what="nginx exit")
        kill_exe(self.bin)


def http_probe(host, path, port=80, timeout=3.0):
    """Minimal HTTP/1.1 GET; returns status code or None."""
    try:
        s = socket.create_connection((host, port), timeout=timeout)
        s.sendall(("GET %s HTTP/1.1\r\nHost: fbench\r\nConnection: close\r\n\r\n" % path).encode())
        data = s.recv(64)
        s.close()
        parts = data.split(b" ")
        return int(parts[1]) if len(parts) > 1 else None
    except (OSError, ValueError):
        return None
